version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - unconvert
    - unparam
    - perfsprint
    - errorlint
    - gosec
    - bidichk
    - noctx
    - whitespace
    - testifylint
    - thelper

formatters:
  enable:
    - gofmt
