// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package briefkit

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Ask provides a mock function for the type MockClient
func (_mock *MockClient) Ask(ctx context.Context, agentID AgentID, prompt string, opts ...AskOption) (*AskResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, agentID, prompt, opts)
	} else {
		tmpRet = _mock.Called(ctx, agentID, prompt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 *AskResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID, string, ...AskOption) (*AskResult, error)); ok {
		return returnFunc(ctx, agentID, prompt, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID, string, ...AskOption) *AskResult); ok {
		r0 = returnFunc(ctx, agentID, prompt, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AskResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AgentID, string, ...AskOption) error); ok {
		r1 = returnFunc(ctx, agentID, prompt, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type MockClient_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID AgentID
//   - prompt string
//   - opts ...AskOption
func (_e *MockClient_Expecter) Ask(ctx interface{}, agentID interface{}, prompt interface{}, opts ...interface{}) *MockClient_Ask_Call {
	return &MockClient_Ask_Call{Call: _e.mock.On("Ask",
		append([]interface{}{ctx, agentID, prompt}, opts...)...)}
}

func (_c *MockClient_Ask_Call) Run(run func(ctx context.Context, agentID AgentID, prompt string, opts ...AskOption)) *MockClient_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AgentID
		if args[1] != nil {
			arg1 = args[1].(AgentID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []AskOption
		var variadicArgs []AskOption
		if len(args) > 3 {
			variadicArgs = args[3].([]AskOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClient_Ask_Call) Return(askResult *AskResult, err error) *MockClient_Ask_Call {
	_c.Call.Return(askResult, err)
	return _c
}

func (_c *MockClient_Ask_Call) RunAndReturn(run func(ctx context.Context, agentID AgentID, prompt string, opts ...AskOption) (*AskResult, error)) *MockClient_Ask_Call {
	_c.Call.Return(run)
	return _c
}
