//go:build !coverage

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package briefkit

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigRepository creates a new instance of MockConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigRepository {
	mock := &MockConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigRepository is an autogenerated mock type for the ConfigRepository type
type MockConfigRepository struct {
	mock.Mock
}

type MockConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigRepository) EXPECT() *MockConfigRepository_Expecter {
	return &MockConfigRepository_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) Exists(ctx context.Context, id AgentID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AgentID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockConfigRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id AgentID
func (_e *MockConfigRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockConfigRepository_Exists_Call {
	return &MockConfigRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockConfigRepository_Exists_Call) Run(run func(ctx context.Context, id AgentID)) *MockConfigRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AgentID
		if args[1] != nil {
			arg1 = args[1].(AgentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigRepository_Exists_Call) Return(b bool, err error) *MockConfigRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockConfigRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id AgentID) (bool, error)) *MockConfigRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) Get(ctx context.Context, id AgentID) (Config, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID) (Config, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID) Config); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Config)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AgentID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfigRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id AgentID
func (_e *MockConfigRepository_Expecter) Get(ctx interface{}, id interface{}) *MockConfigRepository_Get_Call {
	return &MockConfigRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockConfigRepository_Get_Call) Run(run func(ctx context.Context, id AgentID)) *MockConfigRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AgentID
		if args[1] != nil {
			arg1 = args[1].(AgentID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigRepository_Get_Call) Return(config Config, err error) *MockConfigRepository_Get_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockConfigRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id AgentID) (Config, error)) *MockConfigRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) List(ctx context.Context) ([]AgentID, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []AgentID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]AgentID, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []AgentID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AgentID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConfigRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigRepository_Expecter) List(ctx interface{}) *MockConfigRepository_List_Call {
	return &MockConfigRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockConfigRepository_List_Call) Run(run func(ctx context.Context)) *MockConfigRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigRepository_List_Call) Return(agentIDs []AgentID, err error) *MockConfigRepository_List_Call {
	_c.Call.Return(agentIDs, err)
	return _c
}

func (_c *MockConfigRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]AgentID, error)) *MockConfigRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockConfigRepository
func (_mock *MockConfigRepository) Update(ctx context.Context, id AgentID, config Config) error {
	ret := _mock.Called(ctx, id, config)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AgentID, Config) error); ok {
		r0 = returnFunc(ctx, id, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockConfigRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id AgentID
//   - config Config
func (_e *MockConfigRepository_Expecter) Update(ctx interface{}, id interface{}, config interface{}) *MockConfigRepository_Update_Call {
	return &MockConfigRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, config)}
}

func (_c *MockConfigRepository_Update_Call) Run(run func(ctx context.Context, id AgentID, config Config)) *MockConfigRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AgentID
		if args[1] != nil {
			arg1 = args[1].(AgentID)
		}
		var arg2 Config
		if args[2] != nil {
			arg2 = args[2].(Config)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigRepository_Update_Call) Return(err error) *MockConfigRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id AgentID, config Config) error) *MockConfigRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
