//go:build !coverage

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package briefkit

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Spawn provides a mock function for the type MockRunner
func (_mock *MockRunner) Spawn(ctx context.Context, executionId ExecutionID) error {
	ret := _mock.Called(ctx, executionId)

	if len(ret) == 0 {
		panic("no return value specified for Spawn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ExecutionID) error); ok {
		r0 = returnFunc(ctx, executionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Spawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spawn'
type MockRunner_Spawn_Call struct {
	*mock.Call
}

// Spawn is a helper method to define mock.On call
//   - ctx context.Context
//   - executionId ExecutionID
func (_e *MockRunner_Expecter) Spawn(ctx interface{}, executionId interface{}) *MockRunner_Spawn_Call {
	return &MockRunner_Spawn_Call{Call: _e.mock.On("Spawn", ctx, executionId)}
}

func (_c *MockRunner_Spawn_Call) Run(run func(ctx context.Context, executionId ExecutionID)) *MockRunner_Spawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ExecutionID
		if args[1] != nil {
			arg1 = args[1].(ExecutionID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRunner_Spawn_Call) Return(err error) *MockRunner_Spawn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Spawn_Call) RunAndReturn(run func(ctx context.Context, executionId ExecutionID) error) *MockRunner_Spawn_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockRunner
func (_mock *MockRunner) Wait(ctx context.Context, executionId ExecutionID) error {
	ret := _mock.Called(ctx, executionId)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ExecutionID) error); ok {
		r0 = returnFunc(ctx, executionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockRunner_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - executionId ExecutionID
func (_e *MockRunner_Expecter) Wait(ctx interface{}, executionId interface{}) *MockRunner_Wait_Call {
	return &MockRunner_Wait_Call{Call: _e.mock.On("Wait", ctx, executionId)}
}

func (_c *MockRunner_Wait_Call) Run(run func(ctx context.Context, executionId ExecutionID)) *MockRunner_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ExecutionID
		if args[1] != nil {
			arg1 = args[1].(ExecutionID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRunner_Wait_Call) Return(err error) *MockRunner_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Wait_Call) RunAndReturn(run func(ctx context.Context, executionId ExecutionID) error) *MockRunner_Wait_Call {
	_c.Call.Return(run)
	return _c
}
